version: 2.1

orbs:
  yarn: artsy/yarn@dev:2.1.0.a05a433b1dbafce8fca128fc94f90967

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/test
      - yarn/auto-release:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/test
