version: 2.1

orbs:
  yarn: artsy/yarn@4.0.0

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/jest
      - yarn/run:
          name: validate-config
          script: renovate-config-validator
      - yarn/auto-release:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - validate-config
            - yarn/update-cache
            - yarn/jest
