version: 2.1

orbs:
  yarn: artsy/yarn@2.0.0
  auto: auto/release@0.0.1

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/test
      - auto/shipit:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/test
