version: 2.1

orbs:
  yarn: artsy/yarn@dev:2.1.0

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/jest
      - yarn/run:
          name: validate-config
          description: Validates the renovate configuration
          script: renovate-config-validator
      - yarn/auto-release:
          context: npm-deploy
          filters:
            branches:
              only: master
          requires:
            - validate-config
            - yarn/update-cache
            - yarn/test
